// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  app: string;
  caption: string;
  emptyState: string;
  emptyState_placeholder: string;
  operationsWrap: string;
  variant: string;
  variantsWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
