// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  label: string;
  toggler: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
